name: Backend Continuous Deployment
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'starter/backend/**/*'

env:
  PYTHON_VERSION: '3.10'

defaults:
  run:
    working-directory: starter/backend

jobs:
  call-backend-lint:
    name: Backend Lint
    uses: ./.github/workflows/backend-lint-job.yml
    with:
      python-version: '3.10'

  call-backend-test:
    name: Backend Test
    uses: ./.github/workflows/backend-test-job.yml
    with:
      python-version: '3.10'

  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    needs: [call-backend-lint, call-backend-test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AWS_ECR_REGISTRY }}/backend
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: starter/backend
          file: starter/backend/Dockerfile
          push: true
          tags: ${{ env.AWS_ECR_REGISTRY }}/backend:${{ github.sha }},${{ env.AWS_ECR_REGISTRY }}/backend:latest
