name: Backend Continuous Deployment
on:
  workflow_dispatch:

#  push:
#    branches:
#      - main

env:
  PYTHON_VERSION: '3.10'

defaults:
  run:
    working-directory: starter/backend

jobs:
  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: 'pipenv'
          cache-dependency-path: starter/backend/Pipfile.lock

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install Python Dependencies
        run: pipenv install

      - name: Lint
        run: pipenv run test

  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: 'pipenv'
          cache-dependency-path: starter/backend/Pipfile.lock

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install Python Dependencies
        run: pipenv install

      - name: Test
        run: pipenv run test

  backend-build:
    runs-on: ubuntu-latest
    needs: [backend-lint, backend-test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AWS_ECR_REGISTRY }}/backend
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: starter/backend
          file: starter/backend/Dockerfile
          push: true
          tags: ${{ env.AWS_ECR_REGISTRY }}/backend:${{ github.sha }},${{ env.AWS_ECR_REGISTRY }}/backend:latest
