name: frontend-ci

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - "starter/frontend/**"

defaults:
  run:
    working-directory: 'starter/frontend'

jobs:
  lint:
    name: LINT JOB
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: cache modules
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint

  test:
    name: TEST JOB
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: cache modules
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run test

  build:
    name: BUILD JOB
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: success()
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: docker build .
