name: Frontend Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Cache Validation
        uses: actions/cache@v3
        with:
          path: |
            starter/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-udacity-movies   

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm install

      - name: Run lint
        run: |
          cd starter/frontend
          npm run lint

  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Validation
        uses: actions/cache@v3
        with:
          path: |
            starter/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-udacity-movies

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm install

      - name: Run tests
        run: |
          cd starter/frontend
          npm run test

  build-frontend:
    runs-on: ubuntu-latest
    needs: 
      - check-lint
      - run-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Validation
        uses: actions/cache@v3
        with:
          path: |
            starter/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-udacity-movies

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm install

      - name: Run test
        run: |
          cd starter/frontend
          npm run test  

      - name: Build Docker image
        run: |
          cd starter/frontend
          docker build --tag=mp-frontend:latest .     



