# Workflow name
name: Frontend Continuous Integration

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
# Jobs defined in the workflow
jobs:
  lint-and-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Debug message
        run: echo ${{ env.AWS_REGION }}

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

       # Install the dependencies.
      - name: Install the dependencies
        run:  cd starter/frontend && npm ci

      # Run the linter.
     # - run: cd ../../starter/frontend && npm run lint
      - name: Run the linter
        run:  cd starter/frontend && npm run lint
       
      # Run the tests.
      - name: Run tests
        run: cd starter/frontend && npm test

      - name: Debug message
        if: env.DEBUG == 'true'
        run: echo "Debugging is enabled."


    
  build-job:
    runs-on: ubuntu-latest
    needs: lint-and-test-job #dependent job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
