name: Frontend Continuous Integration
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20.x'

defaults:
  run:
    working-directory: starter/frontend

jobs:
  frontend-lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/jobs/frontend-lint-test.yml
        with:
          node-version: ${{env.NODE_VERSION}}

  frontend-build:
    runs-on: ubuntu-latest
    needs: [frontend-lint-test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: starter/frontend

      - name: Build
        run: |
          npm ci
          npm run test
