name: Frontend Test Job
on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node Version'
        required: false
        type: string
        default: '20.x'

defaults:
  run:
    working-directory: starter/frontend

jobs:
  frontend-test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: starter/frontend

      - name: Test
        run: |
          npm ci
          npm run test