name: build-test-mp-frontend
on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20.x'

jobs:
  frontend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        working-directory: starter/frontend

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
        working-directory: starter/frontend

      - name: Lint
        run: |
          npm ci
          npm run lint
        working-directory: starter/frontend

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        working-directory: starter/frontend

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
        working-directory: starter/frontend

      - name: Test
        run: |
          npm ci
          npm run test
        working-directory: starter/frontend

  frontend-build:
    runs-on: ubuntu-latest
    needs: [frontend-lint, frontend-test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        working-directory: starter/frontend

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
        working-directory: starter/frontend

      - name: Build
        run: |
          npm ci
          npm run test
        working-directory: starter/frontend
