name: Frontend Lint Job
on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node Version'
        required: false
        type: string
        default: '20.x'

defaults:
  run:
    working-directory: starter/frontend

jobs:
  frontend-lint:
    name: Lint Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: starter/frontend

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Lint
        run: |
          npm ci
          npm run lint