name: Frontend Continuous Integration
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**/*'
vars:
  NODE_VERSION: '20.x'

defaults:
  run:
    working-directory: starter/frontend

jobs:
  call-frontend-lint:
    name: Lint
    uses: ./.github/workflows/frontend-lint.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}

  call-frontend-test:
    name: Test
    uses: ./.github/workflows/jobs/frontend-test.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}

  frontend-build:
    name: Build
    runs-on: ubuntu-latest
    needs: [call-frontend-lint,call-frontend-test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: starter/frontend

      - name: Build
        run: |
          npm ci
          npm run test
