name: frontend-ci
on:
  workflow_dispatch:

  push:
    branches: ['main']
    paths: ['starter/frontend/**']

  pull_request:
    branches: ['main']
    paths: ['starter/frontend/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

    - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: /starter/frontend/
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

    - name: Install 
      run: npm install
      working-directory: starter/frontend
    
    - name: Lint
      run: npm run lint
      working-directory: starter/frontend


  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

    - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: /starter/frontend/
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

    - name: Install 
      run: npm install
      working-directory: starter/frontend
    
    - name: Test
      run: npm run test
      working-directory: starter/frontend
  
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: steps.lint.outcome == 'success' && steps.test.outcome == 'success'
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

    - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: /starter/frontend/
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

    - name: Install 
      run: npm install
      working-directory: starter/frontend
    
    - name: Test
      run: npm run build
      working-directory: starter/frontend
