name: frontend-ci
on:
  workflow_dispatch:

  push:
    branches: ['main']
    paths: ['starter/frontend/**']

  pull_request:
    branches: ['main']
    paths: ['starter/frontend/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.lint.outputs.status }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Cache node modules
      uses: actions/cache@v2
      id: cache-node-modules
      env:
        cache-name: cache-node-modules
      with:
        path: /starter/frontend/
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install
      run: npm install
      working-directory: starter/frontend
    
    - name: Lint
      id: lint
      run: |
        npm run lint
        echo "status=success" >> "$GITHUB_OUTPUT"
      working-directory: starter/frontend


  test:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.test.outputs.status }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Cache node modules
      uses: actions/cache@v2
      id: cache-node-modules
      env:
        cache-name: cache-node-modules
      with:
        path: /starter/frontend/
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install 
      run: npm install
      working-directory: starter/frontend
    
    - name: Test
      id: test
      run: |
        npm run test
        echo "status=success" >> "$GITHUB_OUTPUT"
      working-directory: starter/frontend
  
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: jobs.lint.status == 'success' && jobs.test.status == 'success'
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Cache node modules
      uses: actions/cache@v2
      id: cache-node-modules
      env:
        cache-name: cache-node-modules
      with:
        path: /starter/frontend/
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install 
      run: npm install
      working-directory: starter/frontend
    
    - name: Test
      run: npm run build
      working-directory: starter/frontend
