name: Frontend Continuous Integration
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20.x'

defaults:
  run:
    working-directory: starter/frontend

jobs:
  frontend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: starter/frontend

      - name: Lint
        run: |
          npm ci
          npm run lint

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: starter/frontend

      - name: Test
        run: |
          npm ci
          npm run test

  frontend-build:
    runs-on: ubuntu-latest
    needs: [frontend-lint, frontend-test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: starter/frontend

      - name: Build
        run: |
          npm ci
          npm run test
